version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7-alpine
    restart: always
    environment:
      - CLICKHOUSE_USER=enbiz
      - CLICKHOUSE_PASSWORD=!Q2w3e4r
    volumes:
      - /mnt/d/Storage-data/clickhouse-data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9941:8123"
      - "9942:9000"
      - "9943:9009"
